name: ask-ubuntu
base: core24
version: '0.0.1'
summary: AI-powered Ubuntu assistant backed by a local LLM
description: |
  Ask Ubuntu is an AI-powered Ubuntu Linux assistant that answers questions
  about your system in a context-aware way. It uses a locally-running LLM
  via Lemonade Server and performs RAG lookups against man pages and Ubuntu
  help documentation.

  Lemonade Server must be running at http://localhost:8000 before launching.

  After installation, connect the required interfaces:

    sudo snap connect ask-ubuntu:system-files-man
    sudo snap connect ask-ubuntu:system-files-dpkg

grade: stable
confinement: strict

# ── Interface declarations ────────────────────────────────────────────────────
plugs:
  shmem:
    interface: shared-memory
    private: true
  # Read man pages and Ubuntu help docs for RAG indexing
  system-files-man:
    interface: system-files
    read:
      - /usr/share/man
      - /usr/share/help

  # Read dpkg/apt data for package status queries (replaces apt/dpkg CLI)
  system-files-dpkg:
    interface: system-files
    read:
      - /var/lib/dpkg
      - /var/lib/apt/lists

# ── Applications ──────────────────────────────────────────────────────────────
apps:
  ask-ubuntu:
    command: bin/ask-ubuntu
    plugs:
      - network            # Connect to Lemonade server at localhost:8000
      - system-observe     # /proc scanning for service detection
      - hardware-observe   # /sys/bus/pci for GPU info, /sys/class/dmi for host
      - desktop-launch     # snapd REST API via /run/snapd.socket
      - system-files-man   # /usr/share/man, /usr/share/help
      - system-files-dpkg  # /var/lib/dpkg, /var/lib/apt/lists
  gui:
    command: usr/bin/ask-ubuntu-gui
    desktop: usr/share/applications/ask-ubuntu-gui.desktop
    extensions: [ gnome ]
    plugs:
      - audio-playback
      - network            # Connect to Lemonade server at localhost:8000
      - system-observe     # /proc scanning for service detection
      - hardware-observe   # /sys/bus/pci for GPU info, /sys/class/dmi for host
      - desktop-launch     # snapd REST API via /run/snapd.socket
      - system-files-man   # /usr/share/man, /usr/share/help
      - system-files-dpkg  # /var/lib/dpkg, /var/lib/apt/lists
      - shmem
    environment:
      TMPDIR: $XDG_RUNTIME_DIR

parts:
  ask-ubuntu:
    plugin: python
    source: .
    python-requirements:
      - requirements.txt
    build-packages:
      - python3-dev    # needed if any pip deps compile from source
    stage-packages:
      - pciutils       # lspci for GPU detection with packaged pci.ids
      - libgomp1       # OpenMP runtime required by faiss-cpu

  ask-ubuntu-gui:
    plugin: nil
    source: electron/
    override-build: |
      npm install
      npm run build
      mkdir -p $SNAPCRAFT_PART_INSTALL/unpacked
      mv dist/linux*-unpacked/* $SNAPCRAFT_PART_INSTALL/unpacked
      mkdir -p "$CRAFT_PART_INSTALL/usr/share/applications"
      cp "$SNAPCRAFT_PROJECT_DIR/electron/ask-ubuntu-gui.desktop" \
         "$CRAFT_PART_INSTALL/usr/share/applications/"
      mkdir -p "$CRAFT_PART_INSTALL/usr/share/icons/hicolor/scalable/apps"
      cp "$SNAPCRAFT_PROJECT_DIR/snap/gui/ask-ubuntu-gui.svg" \
         "$CRAFT_PART_INSTALL/usr/share/icons/hicolor/scalable/apps/"
      mkdir -p "$CRAFT_PART_INSTALL/usr/bin"
      cp "$SNAPCRAFT_PROJECT_DIR/snap/local/ask-ubuntu-gui" \
         "$CRAFT_PART_INSTALL/usr/bin/ask-ubuntu-gui"
      chmod +x "$CRAFT_PART_INSTALL/usr/bin/ask-ubuntu-gui"
    build-packages:
      - nodejs
      - npm
    prime:
      - usr/bin
      - usr/share/icons
      - usr/share/applications
      - unpacked
      - -*/chrome-sandbox
      - -*/resources/app.asar.unpacked/node_modules/sharp/vendor/lib
      - -*/resources/app.asar.unpacked/node_modules/sharp/vendor/include
