name: ask-ubuntu
base: core24
version: '1.0'
summary: AI-powered Ubuntu assistant backed by a local LLM
description: |
  Ask Ubuntu is an AI-powered Ubuntu Linux assistant that answers questions
  about your system in a context-aware way. It uses a locally-running LLM
  via Lemonade Server and performs RAG lookups against man pages and Ubuntu
  help documentation.

  Lemonade Server must be running at http://localhost:8000 before launching.

  After installation, connect the required interfaces:

    sudo snap connect ask-ubuntu:system-files-man
    sudo snap connect ask-ubuntu:system-files-dpkg

grade: devel
confinement: strict

# ── Interface declarations ────────────────────────────────────────────────────
plugs:
  # Read man pages and Ubuntu help docs for RAG indexing
  system-files-man:
    interface: system-files
    read:
      - /usr/share/man
      - /usr/share/help

  # Read dpkg/apt data for package status queries (replaces apt/dpkg CLI)
  system-files-dpkg:
    interface: system-files
    read:
      - /var/lib/dpkg
      - /var/lib/apt/lists

# ── Applications ──────────────────────────────────────────────────────────────
apps:
  ask-ubuntu:
    command: bin/ask-ubuntu
    plugs:
      - network            # Connect to Lemonade server at localhost:8000
      - home               # Read/write ~/.cache for FAISS index & history
      - system-observe     # /proc scanning for service detection
      - hardware-observe   # /sys/bus/pci for GPU info, /sys/class/dmi for host
      - desktop-launch     # snapd REST API via /run/snapd.socket
      - system-files-man   # /usr/share/man, /usr/share/help
      - system-files-dpkg  # /var/lib/dpkg, /var/lib/apt/lists

# ── Build ─────────────────────────────────────────────────────────────────────
parts:
  ask-ubuntu:
    plugin: python
    source: .
    python-requirements:
      - requirements.txt
    build-packages:
      - python3-dev    # needed if any pip deps compile from source
    stage-packages:
      - pciutils       # lspci for GPU detection with packaged pci.ids
      - libgomp1       # OpenMP runtime required by faiss-cpu
